### ISSUE TITLE
os.mkdir('{path_home}/.stellarium/scripts') not work

### ISSUE THREAD

**Issue by sugizo** [beltoforion/kalstar#4]
**code**
```
    if not os.path.isdir(f'{path_home}/.stellarium/scripts'):
        os.mkdir('{path_home}/.stellarium/scripts')
```

not work

**steps** 
```
sudo apt update
sudo apt install -y vlc ffmpeg stellarium git python3
git clone https://github.com/beltoforion/kalstar
python3 kalstar/kalstar.py -lat 52.5186 -long 13.4083 -t "Look at all the Stars!" -d 2023-10-02 -fps 30 -ts 2 -dt 30 -az 90 -alt 25 -fov 70 -o out.mp4
```

return an error
```
kalstar - A star motion video generator:
-------------------------------------------
Python Version: sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Date: 2023-10-02
Title: "Look at all the Stars!"
Simulation time span: 2.0
Height: 25.0
View Direction: 90.0
Position: long=13.4083; lat=52.5186
Stellarium does not seem to be installed!
Traceback (most recent call last):
  File "/content/kalstar/kalstar.py", line 356, in <module>
    main()
  File "/content/kalstar/kalstar.py", line 348, in main
    os.mkdir('{path_home}/.stellarium/scripts')
FileNotFoundError: [Errno 2] No such file or directory: '{path_home}/.stellarium/scripts'
```

so users must created it manually
`mkdir -p ~/.stellarium/scripts`

best regards

**Comment by beltoforion** [comment]
fixed
