### ISSUE TITLE
UnboundLocalError: local variable 'sunrise_t' referenced before assignment if longitude more than 100, or latitude have negative value

### ISSUE THREAD

**Issue by sugizo** [beltoforion/kalstar#7]
**step**
```
sudo apt update
sudo apt install -y vlc ffmpeg stellarium git python3
git clone https://github.com/beltoforion/kalstar
mkdir -p ~/.stellarium/scripts
python3 kalstar/kalstar.py -lat 35.6762 -long 139.6503 -t "tokyo" -d 2023-10-02 -fps 10 -ts 2 -dt 10 -az 90 -alt 25 -fov 70 -o out.mp4
```

**result**
```
kalstar - A star motion video generator:
-------------------------------------------
Python Version: sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)
Date: 2023-10-02
Title: "tokyo"
Simulation time span: 2.0
Height: 25.0
View Direction: 90.0
Position: long=139.6503; lat=35.6762
Traceback (most recent call last):
  File "/home/sugizo/kalstar/kalstar.py", line 356, in <module>
    main()
  File "/home/sugizo/kalstar/kalstar.py", line 351, in main
    sa.create_script()
  File "/home/sugizo/kalstar/kalstar.py", line 248, in create_script
    sunset_time = s.sunset(self.__args.date)
  File "/home/sugizo/kalstar/kalstar.py", line 46, in sunset
    self.__calc()
  File "/home/sugizo/kalstar/kalstar.py", line 133, in __calc
    sunrise_t += 1
UnboundLocalError: local variable 'sunrise_t' referenced before assignment
```

best regards

**Comment by beltoforion** [comment]
confirmed

**Comment by beltoforion** [comment]
should  be fixed
